### ISSUE TITLE
Feature request: Option to set default global for posts

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/WDS-Simple-Page-Builder#1]
If a post does not have any parts assigned to it then have a repeatable field group on plugin's settings page to allow user to set default parts to display.

**Comment by colorful-tones** [comment]
Bonus points if the setting is optional
![selfie-0](http://i.imgur.com/0p5SUHn.gif)

**Comment by jazzsequence** [comment]
This was added in 5b45c65cec6e84e91e5fb36adfe464a2ee63fe4f
