### ISSUE TITLE
Display 'Layout Name' as accordion heading title for Saved Layouts

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/WDS-Simple-Page-Builder#10]
If you have multiple Saved Layouts, and all their accordion items are expanded the screen gets long. However, if you collapse them all to try and simplify the ui, and visual clutter then all you see is: "Layout 1", "Layout 2", "Layout 3", etc. (see screenshot https://www.dropbox.com/s/oz64gxgjx078tph/Screenshot%202015-07-14%2011.14.08.png?dl=0) 

Would be nice to use the designated Layout Name field to also update the title in the accordion so at least you know which layout is which when you collapse?

**Comment by colorful-tones** [comment]
Also, I noticed that collapsing/expanding does not persist. So if you collapse some in order to try and simplify screen real-estate, but then update (click 'Save') an option you'll get them all expanded again :panda_face:

**Comment by jazzsequence** [comment]
Yeah, I took a stab at that (changing the titles) briefly and it failed miserably, but I might swing back to it at some point.

**Comment by jazzsequence** [comment]
Creating a separate ticket for the collapsing/expanding thing. #18
