### ISSUE TITLE
Load template parts from inside a plugin

### ISSUE THREAD

**Issue by jazzsequence** [WebDevStudios/WDS-Simple-Page-Builder#15]
It would be cool if a plugin could add template parts to the list of template parts PB uses, so all functionality could be contained inside the plugin. Ultimately, this would prevent parts of the page from being broken if there was a badly written template part that was dependant upon a plugin that was disabled.

**Comment by jtsternberg** [comment]
We should look to BuddyPress for prior art.

**Comment by dustyf** [comment]
On a side note, but related, when loading from a theme maybe we should allow Child Themes to load them too.  get_template_directory returns the parent theme.  We should probably have it so it overrides Child > Parent > Plugin.

**Comment by jazzsequence** [comment]
This is now working in `refactor-2` and will soon be added to `develop`. Props @modemlooper.
