### ISSUE TITLE
Interface wastes a lot of space

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/WDS-Simple-Page-Builder#17]
Im not sure this is related to this plugin directly or CMB2, either way I was wondering if this is something you would be welcoming a PR to improve things a little.

Attached bellow is a screenshot of how much space could be spared, probably making the interface just a bit more intuitive in the process.

![slice 1](https://cloud.githubusercontent.com/assets/151981/8888993/0c7aaa20-32bd-11e5-943e-ec68b993e8ee.png)

**Comment by jazzsequence** [comment]
Yeah, we're pretty much using stock CMB2 CSS. I'd absolutely welcome a PR if you wanted to have a go at cleaning it up. :)

**Comment by lmartins** [comment]
I'll have a go at it. Im very much interested in using your library, I might as well try to improve this ;)
Maybe an opportunity to move from ACF to CMB2 also, we will see.

**Comment by jazzsequence** [comment]
#18 is somewhat related

**Comment by jazzsequence** [comment]
CMB is pretty well documented but it's always lacked drag and drop support. I'm sure if you get that part working there will be a lot of people who are eternally grateful :laughing:

**Comment by lmartins** [comment]
Ok, i'll have to study CMB2 library because it seems the layout shown on Simple Page Builder is pretty much the default for CMB2.

**Comment by jtsternberg** [comment]
FYI, we're working on an API to allow additional field registration for parts (https://github.com/WebDevStudios/WDS-Simple-Page-Builder/issues/19#issuecomment-128056626). @briannaorg is working on some UI/UX updates for that. I'm not sure how much we can change the UI without breaking the additional fields functionality and styling for those additional fields. Something to keep in mind.

**Comment by lmartins** [comment]
Thank you @jtsternberg 
I do get this has a lot of implications and far from straightforward. Please take it as a suggestion more than a complaint ;)

Im closing this for now and maybe reopen when Im able to provide a more useful contribution. 

About the new functionality being introduced with https://github.com/WebDevStudios/WDS-Simple-Page-Builder/issues/19, all I can say is WOW, this adds a lot of flexibility to the whole system, can't wait to try it.

Thank you both.
