### ISSUE TITLE
collapsing/expanding does not persist

### ISSUE THREAD

**Issue by jazzsequence** [WebDevStudios/WDS-Simple-Page-Builder#18]
Originally reported by @colorful-tones in #10

> if you collapse some in order to try and simplify screen real-estate, but then update (click 'Save') an option you'll get them all expanded again :panda_face:

**Comment by blobaugh** [comment]
@colorful-tones in pull request #51 I set it up so the saved layouts parts are always collapsed on page load. This should save a good amount of screen real estate. Unfortunately cmb does not have a way to remember the collapsed/expanded states of the individual fields. 

Is this more like what you are wanting or is it now hiding too much information?

**Comment by jazzsequence** [comment]
@blobaugh do the parts expand if you've expanded them previously (e.g. does it "remember" if you've opened them, or does it always default to closed)?

**Comment by blobaugh** [comment]
It does not remember. They will always be closed

**Comment by jazzsequence** [comment]
Would like to hear from @colorful-tones whether always closed works. I would prefer it to remember open/closed state so it behaves like core WordPress meta boxes.

**Comment by blobaugh** [comment]
The metabox itself does behave that way. It is the stuff inside the metabox that is different. If we make the groups remember their expanded state that maybe be something we should contribute back into CMB2 itself also.

**Comment by colorful-tones** [comment]
Hmm, that is a hard one. If collapse/expand can not persist, and we're opting to close on initial load it may confuse users if they don't see the options available within the area. They might not even think to expand even. But, I also like the idea of having simple, cleaner UI on initial load.

I'm on the fence.

**Comment by blobaugh** [comment]
Maybe on initial load the fields can be closed and after the page is rendered it can retrieve a cookie of how the user had the groups expanded/collapsed last time and do it.
That could be a decent compromise and would not require any coordination with CMB2

**Comment by jtsternberg** [comment]
This would be a good (and not too difficult) addition to CMB2.

**Comment by jazzsequence** [comment]
@blobaugh IIRC the way WordPress core does it is by saving a setting in usermeta for the toggle states of the different meta boxes. They might use a cookie as well, not sure.

Agree with @jtsternberg this could/should go into CMB2 and therefore get rolled into Page Builder with a CMB2 update.

Closing this and created a new ticket in CMB2: https://github.com/WebDevStudios/CMB2/issues/490

**Comment by blobaugh** [comment]
FYI this is not the main metabox, but rather the sub areas inside the metabox
