### ISSUE TITLE
Do not conditionally load init.php based on CMB2_LOADED.

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-Simple-Page-Builder#20]
By wrapping in the CMB2_LOADED check you are short-circuiting CMB2's system for ensuring the newest version is loaded. https://github.com/WebDevStudios/WDS-Simple-Page-Builder/blob/master/wds-simple-page-builder.php#L36-L38
the check is not needed and will provide a bad precedent for other devs who use this lib as an example to follow.

**Comment by jazzsequence** [comment]
Fixed in 7ff33858cfc5c516c4682d941ccd6abb13795e77

Will be part of the 1.6 update

**Comment by jtsternberg** [comment]
:thumbsup:
