### ISSUE TITLE
Parent theme loads parts from parent

### ISSUE THREAD

**Issue by jazzsequence** [WebDevStudios/WDS-Simple-Page-Builder#21]
Brought up in #16. Currently parent theme will load parts from the parent theme but the part _names_ from the child.

**Comment by jazzsequence** [comment]
Found the issue, fixed in 31ec4a3b8a3e091983ddffbeeb593429811bbf2b
`get_stylesheet_directory` is used in `options.php` but when we check the existence of the file, we're using `get_template_directory`. fix the inconsistency so we're always looking in the parent by default

**Comment by lmartins** [comment]
I think this might be the reason for another issue im facing.

I have a custom post type (events) which has the corresponding archive file `archive-event.php`. In there im trying to load a named layout:

``` php
do_action( 'wds_page_builder_load_parts', 'events-layout' );
```

Despite this website having a named layout with such name, nothing gets outputted with the code above. 

If you remember if that crazy person using parent/child themes quite extensively, so I wonder if that has any relation to this.

**Comment by jazzsequence** [comment]
The layout name has no connection to the template part name. Not seeing what template parts are saved in the `events-layout` layout, I could only guess at a reason why the template is not loading for you. Also, this fix has not been merged into master yet, it only exists on the develop branch. But I think you're misunderstanding the recommended way to build and use template parts. (See [Building Template Parts for Page Builder](https://github.com/WebDevStudios/WDS-Simple-Page-Builder/wiki/Building-Template-Parts-for-Page-Builder))

The general rule of thumb is that you would _never_ want a template part that is used by Page Builder to break the page. A template part that contains a loop which assumes a specific post type would violate this rule. What happens if you are using the archive-event template part on a regular page or blog post? Best case scenario, you have an HTML structure that doesn't match the content, but worst case scenario you introduce errors in the page or conflicts created by having multiple Loops on a page without resetting the query. If you wanted to have a template part that displayed events on _any_ page, you probably wouldn't use the main `archive-event.php` template, but, instead, would use a wrapper template that set up the Loop inside that (for example `part-events.php`) and inside that template you'd use `get_template_part( 'archive', 'event' )`. That way, you can be sure that you're not going to potentially break your site if a user decides to put this awesome Archive Event template part into some random page they're working on.

**Comment by lmartins** [comment]
Thank you Chris for the detailed explanation.
I've checked out the `develop` branch and it works just fine now. I believe my template parts are pretty self contained but it is good to be aware of what you explain. 

Thanks again, cheers.

**Comment by jazzsequence** [comment]
Most likely, though, your specific template parts that deal with content that assumes a particular post type would never be a template part that is usable by Page Builder unless you're feeding it a specific query before running the Loop.

**Comment by lmartins** [comment]
Yes, the two cases i've dealt with so far have custom loops passed into them.

**Comment by jazzsequence** [comment]
:+1:
