### ISSUE TITLE
Can only display one (of the same) template parts per page

### ISSUE THREAD

**Issue by gregrickaby** [WebDevStudios/WDS-Simple-Page-Builder#26]
If you select the same template part for more than one area, only the first one loads.

**Comment by jtsternberg** [comment]
Does this not fix it? https://github.com/WebDevStudios/WDS-Simple-Page-Builder/commit/e6a3ffb333cfbac5e581d46f492e3164a7b8fb67

**Comment by dustyf** [comment]
I've put the updated version of develop on our project, @gregrickaby.  Could you try this out again and see if there are still any issues?

**Comment by gregrickaby** [comment]
Looks like it's fixed (in develop)
