### ISSUE TITLE
Registering Areas Permanent

### ISSUE THREAD

**Issue by aubreypwd** [WebDevStudios/WDS-Simple-Page-Builder#27]
Once you use `register_page_builder_area()` to create an area, it persists.

**Comment by gregrickaby** [comment]
Just doing some digging, I noticed that area's are defined in the options table...

https://www.dropbox.com/s/owoo3nnvm4gbl0o/Screenshot%202015-08-10%2014.13.59.png?dl=0

**Comment by dustyf** [comment]
Should be fixed in branch feature/refactor-2.  This will be merged to develop after more testing.

**Comment by jazzsequence** [comment]
Yep, this is fixed in `refactor-2` and will be merged into `develop` soon. Props @dustyf.
