### ISSUE TITLE
wds_page_builder_get_part_data does not get meta values for areas

### ISSUE THREAD

**Issue by dustyf** [WebDevStudios/WDS-Simple-Page-Builder#29]
wds_page_builder_get_part_data() only looks in the meta key '_wds_builder_template' but when you add parts to areas, it puts that meta under a key with the area appended like '_wds_builder_footer_template'.  

So, this does not return the proper meta data from fields within declared areas for the page builder, only within the main area.

**Comment by jazzsequence** [comment]
this is fixed in **develop**

thanks @dustyf
