### ISSUE TITLE
Saved Layouts - cannot remove a saved layout after creating

### ISSUE THREAD

**Issue by colorful-tones** [WebDevStudios/WDS-Simple-Page-Builder#3]
I see the 'Remove Layout' button, but appears inactive even though I created and saved a new 'Saved Layout', therefore I can not actually remove the layout.

**Comment by jazzsequence** [comment]
Yeah, you can remove additional layouts, but once you add one, you can't get rid of it. It doesn't help that the name field is required otherwise you could just blank out the fields...I might just remove the required attribute for the short term.

**Comment by jazzsequence** [comment]
maybe a CMB2 thing?

**Comment by jazzsequence** [comment]
Sort of fixed in 6333021bdb0a863aac11319af43bb57d78ec16e1

Removed the required attribute, anyway.

**Comment by jazzsequence** [comment]
Related to this CMB2 issue https://github.com/WebDevStudios/CMB2/issues/312
