### ISSUE TITLE
Parts index not being set properly, causing meta values not being returned

### ISSUE THREAD

**Issue by dustyf** [WebDevStudios/WDS-Simple-Page-Builder#33]
https://github.com/WebDevStudios/WDS-Simple-Page-Builder/blob/develop/inc/template-tags.php#L518  

The part index in here is always returning zero when we are trying to get values for fields in template parts.  This is not getting iterated or set when looping through builder parts, so the proper meta values are not being returned.

**Comment by jazzsequence** [comment]
merged into **develop**

thanks @dustyf
