### ISSUE TITLE
Unable to display data from field type "file"

### ISSUE THREAD

**Issue by briannaorg** [WebDevStudios/WDS-Simple-Page-Builder#35]
Using the field type "file" in a field array prevents any page builder parts from displaying on the front end. 
Data for a meta box using this field type successfully saves, displays in the admin, but doesn't display on the front end and prevents all other page parts from displaying.

**Comment by jazzsequence** [comment]
I think this is fixed now because @gregrickaby just did this on a project today. It's possible the fix wasn't pushed to Github though... @dustyf do you have any thoughts/ideas?

**Comment by dustyf** [comment]
I believe this is now fixed as well,  With the new feature/refactor-2 branch Brianna reported her fields as working.

**Comment by briannaorg** [comment]
Yes, the version on refactor-2 branch works with the file fieldtype. Woo!
