### ISSUE TITLE
Allow parts to be used multiple times

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-Simple-Page-Builder#48]
This is key to making #19 invaluable. Allowing a the same template part to used multiple times, but w/ different configurations will allow things like custom loops for different categories, etc. 

This broke in this commit: https://github.com/WebDevStudios/WDS-Simple-Page-Builder/commit/401fcf8d9f8ecd3b9ebde172fd588331f71aa1d1

**Comment by JayWood** [comment]
Fixed in devleop branch at 33e563fe107d4bb116e027fbfa9b916acc2fdd18
