### ISSUE TITLE
Allow code-configuration of per-cpt defaults

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/WDS-Simple-Page-Builder#6]
For devs to pre-define some defaults w/o having to setup in every site/db.

**Comment by jazzsequence** [comment]
:boom: https://github.com/WebDevStudios/WDS-Simple-Page-Builder/wiki/Registering-Layouts

Also, layouts can be created one-time without saving them ([documentation here](https://github.com/WebDevStudios/WDS-Simple-Page-Builder/wiki/Template-Tags#wds_page_builder_load_parts-parts---))

```
wds_page_builder_load_parts( array(
      'part-1',
      'part-2',
      'part-3',
) );
```

Added in 1.3.

**Comment by jtsternberg** [comment]
:boom: indeed!
