### ISSUE TITLE
Since update to 1.6 php permission denied

### ISSUE THREAD

**Issue by marsshall** [WebDevStudios/WDS-Simple-Page-Builder#61]
Hi, since I update to your 1.6 develop version, I have trouble to work my wds-simple page builder. 

Throw this error in my single template: http://i.imgur.com/7LJJ2IS.png

Calling page builder area with: <?php wds_page_builder_area('review'); ?>

Using this page builder options: http://i.imgur.com/7pHCzsG.png

Thank in advance.

**Comment by jazzsequence** [comment]
@marsshall That looks like a permissions issue. I would check to make sure the /parts directory in your theme exists and that your server (I'm guessing local dev environment on Windows?) has permission to access the files in that directory.

**Comment by rianbotha** [comment]
I'm having the same issue (local dev on Windows).
If I just manually include the template part using require() it works, but using wds_page_builder_area() I get 
`Warning: require(D:\xampp\htdocs\site\wp-content\themes\theme\parts): failed to open stream: Permission denied in D:\xampp\htdocs\wordpress\wp-includes\template.php on line 564

Fatal error: require(): Failed opening required 'D:\xampp\htdocs\site/wp-content/themes/theme/parts/' (include_path='.;C:\xampp\php\PEAR') in D:\xampp\htdocs\site\wp-includes\template.php on line 564`

**Comment by rianbotha** [comment]
It would appear that the issue relates to the path for the template part being wrapped in esc_url(), which then returns a blank file path. Line 419 in class-wds-page-builder-options.php

**Comment by jazzsequence** [comment]
@rianbotha @marsshall this should be fixed now. just changed the sanitization function.
