### ISSUE TITLE
A way to create saved layouts without need for database

### ISSUE THREAD

**Issue by ajgagnon** [WebDevStudios/WDS-Simple-Page-Builder#62]
Just wondering since the register_page_builder_layout function is deprecated, is there any other way to create default layouts without creating custom post types? Ideally, default layouts would come loaded with the theme and not be dependent on each site's database. 

Thanks again for an awesome plugin!

**Comment by jazzsequence** [comment]
It's deprecated for now, but we could try to bring it back at a later date. Basically, `register_page_builder_layout` would need to check if a layout CPT with that name exists and create your layout CPT for you if it doesn't using `wp_insert_post` and then add the post meta for the template parts. If you want to try submitting a PR for the purpose, I'd be happy to give it a look. :)
