### ISSUE TITLE
Plugin is not compatible with WP 4.7

### ISSUE THREAD

**Issue by palicko** [WebDevStudios/WDS-Simple-Page-Builder#68]
Plugin returns multiple errors
`Warning: ksort() expects parameter 1 to be array, object given in /wp-content/plugins/WDS-Simple-Page-Builder/inc/template-tags.php on line 283`
`Warning: array_merge() expects at least 1 parameter, 0 given in /wp-content/plugins/WDS-Simple-Page-Builder/inc/class-wds-page-builder-options.php on line 375`
`Warning: Invalid argument supplied for foreach() in /wp-content/plugins/WDS-Simple-Page-Builder/inc/class-wds-page-builder-options.php on line 396`
and so on...

And here is what caused it, hooks were reworked: https://make.wordpress.org/core/2016/09/08/wp_hook-next-generation-actions-and-filters/

Can you please fix it?

Thanks!

**Comment by rianbotha** [comment]
I've just submitted a pull request to fix this issue.
You can grab the fix from my fork in the meantime. 
\inc\template-tags.php was the only file changed.

**Comment by jasperf** [comment]
Would be great to have this pull merged.
