### ISSUE TITLE
github submodules don't exist in zips :(

### ISSUE THREAD

**Issue by scottwyden** [WebDevStudios/WDS-Simple-Page-Builder#8]
On a fresh instance on GoDaddy's new "Pro" Managed Host (test server) I get the following upon trying to activate:

Warning: require_once(/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php): failed to open stream: No such file or directory in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

Fatal error: require_once(): Failed opening required '/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

Fatal error: require_once(): Failed opening required '/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

**Comment by jazzsequence** [comment]
Hey @scottwyden 
Did you clone the repo or did you download the zip file? If you cloned, you might not be getting the cmb2 submodule.

**Comment by scottwyden** [comment]
I downloaded it from here, not a clone.

**Comment by jazzsequence** [comment]
do you have a `inc/cmb2` folder?

**Comment by jtsternberg** [comment]
Instead of downloading (github doesn't include submodules when downloading), you should recursively clone this repo (`git clone --recursive https://github.com/WebDevStudios/WDS-Simple-Page-Builder.git`)

**Comment by jazzsequence** [comment]
@jtsternberg really? it doesn't? I thought it did. :/

**Comment by jazzsequence** [comment]
...that could be why it hasn't been picked up by the WP.org repo yet :'(

**Comment by scottwyden** [comment]
inc/cmb2 folder does exist, but nothing is inside of it.

**Comment by jazzsequence** [comment]
@scottwyden @jtsternberg is right. I just downloaded the archive and /inc/cmb2 is empty. You're missing a crucial component of the plugin because GitHub isn't including the submodule in the zip files. I'll need to manage the CMB2 stuff manually and not use a submodule.

**Comment by jazzsequence** [comment]
@scottwyden try redownloading now

**Comment by jtsternberg** [comment]
@jazzsequence for WDS Twitter Widget, I use a grunt task to compile a .zip file to be used in the repo (and still use submodules). https://github.com/WebDevStudios/WDS-Twitter-Widget

**Comment by scottwyden** [comment]
Unfortunately I'm still getting an error.

Warning: require_once(/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php): failed to open stream: No such file or directory in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

Fatal error: require_once(): Failed opening required '/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

Fatal error: require_once(): Failed opening required '/home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder//inc/cmb2/init.php' (include_path='.:/usr/local/php5_4/lib/php') in /home/content/p3pnexwpnas07_data03/82/2695782/html/wp-content/plugins/WDS-Simple-Page-Builder/wds-simple-page-builder.php on line 37

**Comment by jazzsequence** [comment]
@scottwyden yeah, sorry, that didn't re-add the directory. just pushed it up and it should work now. :S

**Comment by scottwyden** [comment]
:-) Trying

**Comment by scottwyden** [comment]
All good now! Thanks guys.

**Comment by jazzsequence** [comment]
woot! :)
